github=https://github.com/grace-plugins/grace-dynamic-modules
authors=Michael Yan
title=Grace Dynamic Modules
subtitle=Grace Dynamic Modules offer new ways of creating modular and maintainable Grace applications
copyright=Copyright &copy; 2022-2025 Michael Yan. The content is licensed under a Creative Commons Attribution 4.0 International (CC BY SA 4.0) license.